/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BuyerIntent = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'constraintsJson' : IDL.Text,
  'buyerId' : IDL.Nat,
  'requestedQuantity' : IDL.Nat,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'fixtureId' : IDL.Opt(IDL.Nat),
  'createdAt' : IDL.Int,
  'settlementStatus' : IDL.Text,
  'agreedPrice' : IDL.Float64,
  'buyerIntentId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'sellerProductOfferId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const SellerProductOffer = IDL.Record({
  'id' : IDL.Nat,
  'termsSummary' : IDL.Text,
  'serviceScore' : IDL.Nat,
  'shippingTimeDays' : IDL.Nat,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'qualityScore' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'warrantyMonths' : IDL.Nat,
  'sellerId' : IDL.Nat,
  'priceOffer' : IDL.Float64,
  'priceMrp' : IDL.Float64,
  'quantityAvailable' : IDL.Nat,
});
export const AdminOperationLog = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'summary' : IDL.Text,
  'triggeredBy' : IDL.Text,
  'operation' : IDL.Text,
});
export const SessionTxn = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'eventPayload' : IDL.Text,
  'nonce' : IDL.Text,
  'buyerId' : IDL.Opt(IDL.Nat),
  'sellerId' : IDL.Opt(IDL.Nat),
  'nonceSuffix' : IDL.Text,
  'sessionId' : IDL.Text,
  'eventType' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'SELLER' : IDL.Null,
  'BUYER' : IDL.Null,
  'VIEWER' : IDL.Null,
  'ADMIN' : IDL.Null,
});
export const UserWithoutMobile = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'principal' : IDL.Principal,
  'alias' : IDL.Opt(IDL.Text),
  'hashedIdentity' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'role' : AppRole,
  'businessName' : IDL.Opt(IDL.Text),
  'maskedTag' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
});
export const OperationResult = IDL.Record({
  'total' : IDL.Nat,
  'updated' : IDL.Nat,
});
export const AutoMatchResult = IDL.Record({
  'skipped' : IDL.Nat,
  'matched' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'principal' : IDL.Principal,
  'alias' : IDL.Opt(IDL.Text),
  'hashedIdentity' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'role' : AppRole,
  'businessName' : IDL.Opt(IDL.Text),
  'maskedTag' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'mobile' : IDL.Opt(IDL.Text),
});
export const Fixture = IDL.Record({
  'id' : IDL.Nat,
  'groupBSellerIds' : IDL.Vec(IDL.Nat),
  'status' : IDL.Text,
  'startsAt' : IDL.Int,
  'groupASellerIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'endsAt' : IDL.Int,
  'scoringFormulaVersion' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'baseSkuCode' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'attributes' : IDL.Text,
  'category' : IDL.Text,
});
export const SessionMerkleRoot = IDL.Record({
  'id' : IDL.Nat,
  'numLeaves' : IDL.Nat,
  'createdAt' : IDL.Int,
  'merkleRootHash' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const LeaderboardEntry = IDL.Record({
  'id' : IDL.Nat,
  'priceScore' : IDL.Float64,
  'fixtureId' : IDL.Nat,
  'warrantyScore' : IDL.Float64,
  'overallScore' : IDL.Float64,
  'serviceScore' : IDL.Float64,
  'createdAt' : IDL.Int,
  'rank' : IDL.Nat,
  'productId' : IDL.Nat,
  'qualityScore' : IDL.Float64,
  'isWinner' : IDL.Bool,
  'sellerId' : IDL.Nat,
});
export const AppUser = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'principal' : IDL.Principal,
  'alias' : IDL.Opt(IDL.Text),
  'hashedIdentity' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'role' : AppRole,
  'businessName' : IDL.Opt(IDL.Text),
  'maskedTag' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'mobile' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveUser' : IDL.Func([IDL.Nat], [], []),
  'adminListAllIntents' : IDL.Func([], [IDL.Vec(BuyerIntent)], ['query']),
  'adminListAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'adminListAllOffers' : IDL.Func([], [IDL.Vec(SellerProductOffer)], ['query']),
  'adminListOperationLogs' : IDL.Func(
      [],
      [IDL.Vec(AdminOperationLog)],
      ['query'],
    ),
  'adminListSessionTxns' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SessionTxn)],
      ['query'],
    ),
  'adminListUsers' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(UserWithoutMobile)],
      ['query'],
    ),
  'adminRecomputeLeaderboard' : IDL.Func([], [OperationResult], []),
  'adminRunAutoMatching' : IDL.Func([], [AutoMatchResult], []),
  'adminSetUserActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBuyerIntent' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createFixture' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Nat),
        IDL.Int,
        IDL.Int,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createLeaderboardEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'createMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Float64, IDL.Nat],
      [],
      [],
    ),
  'createOffer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFixture' : IDL.Func([IDL.Nat], [IDL.Opt(Fixture)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserWithoutMobile)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getSessionMerkleRoot' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SessionMerkleRoot)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listFixtures' : IDL.Func([], [IDL.Vec(Fixture)], ['query']),
  'listLeaderboardByFixture' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'listMatchesForSeller' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'listMyIntents' : IDL.Func([], [IDL.Vec(BuyerIntent)], ['query']),
  'listMyMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'listMyOffers' : IDL.Func([], [IDL.Vec(SellerProductOffer)], ['query']),
  'listMySessionTxns' : IDL.Func([IDL.Text], [IDL.Vec(SessionTxn)], ['query']),
  'listOffersByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SellerProductOffer)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'registerBuyer' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [AppUser],
      [],
    ),
  'registerSeller' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AppUser], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSessionMerkleRoot' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateFixtureStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateIntentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateMatchStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOffer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BuyerIntent = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'constraintsJson' : IDL.Text,
    'buyerId' : IDL.Nat,
    'requestedQuantity' : IDL.Nat,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'fixtureId' : IDL.Opt(IDL.Nat),
    'createdAt' : IDL.Int,
    'settlementStatus' : IDL.Text,
    'agreedPrice' : IDL.Float64,
    'buyerIntentId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'sellerProductOfferId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const SellerProductOffer = IDL.Record({
    'id' : IDL.Nat,
    'termsSummary' : IDL.Text,
    'serviceScore' : IDL.Nat,
    'shippingTimeDays' : IDL.Nat,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'qualityScore' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'warrantyMonths' : IDL.Nat,
    'sellerId' : IDL.Nat,
    'priceOffer' : IDL.Float64,
    'priceMrp' : IDL.Float64,
    'quantityAvailable' : IDL.Nat,
  });
  const AdminOperationLog = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'summary' : IDL.Text,
    'triggeredBy' : IDL.Text,
    'operation' : IDL.Text,
  });
  const SessionTxn = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'eventPayload' : IDL.Text,
    'nonce' : IDL.Text,
    'buyerId' : IDL.Opt(IDL.Nat),
    'sellerId' : IDL.Opt(IDL.Nat),
    'nonceSuffix' : IDL.Text,
    'sessionId' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'SELLER' : IDL.Null,
    'BUYER' : IDL.Null,
    'VIEWER' : IDL.Null,
    'ADMIN' : IDL.Null,
  });
  const UserWithoutMobile = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'principal' : IDL.Principal,
    'alias' : IDL.Opt(IDL.Text),
    'hashedIdentity' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'role' : AppRole,
    'businessName' : IDL.Opt(IDL.Text),
    'maskedTag' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
  });
  const OperationResult = IDL.Record({
    'total' : IDL.Nat,
    'updated' : IDL.Nat,
  });
  const AutoMatchResult = IDL.Record({
    'skipped' : IDL.Nat,
    'matched' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'principal' : IDL.Principal,
    'alias' : IDL.Opt(IDL.Text),
    'hashedIdentity' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'role' : AppRole,
    'businessName' : IDL.Opt(IDL.Text),
    'maskedTag' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'mobile' : IDL.Opt(IDL.Text),
  });
  const Fixture = IDL.Record({
    'id' : IDL.Nat,
    'groupBSellerIds' : IDL.Vec(IDL.Nat),
    'status' : IDL.Text,
    'startsAt' : IDL.Int,
    'groupASellerIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'endsAt' : IDL.Int,
    'scoringFormulaVersion' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'baseSkuCode' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'attributes' : IDL.Text,
    'category' : IDL.Text,
  });
  const SessionMerkleRoot = IDL.Record({
    'id' : IDL.Nat,
    'numLeaves' : IDL.Nat,
    'createdAt' : IDL.Int,
    'merkleRootHash' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const LeaderboardEntry = IDL.Record({
    'id' : IDL.Nat,
    'priceScore' : IDL.Float64,
    'fixtureId' : IDL.Nat,
    'warrantyScore' : IDL.Float64,
    'overallScore' : IDL.Float64,
    'serviceScore' : IDL.Float64,
    'createdAt' : IDL.Int,
    'rank' : IDL.Nat,
    'productId' : IDL.Nat,
    'qualityScore' : IDL.Float64,
    'isWinner' : IDL.Bool,
    'sellerId' : IDL.Nat,
  });
  const AppUser = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'principal' : IDL.Principal,
    'alias' : IDL.Opt(IDL.Text),
    'hashedIdentity' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'role' : AppRole,
    'businessName' : IDL.Opt(IDL.Text),
    'maskedTag' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'mobile' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveUser' : IDL.Func([IDL.Nat], [], []),
    'adminListAllIntents' : IDL.Func([], [IDL.Vec(BuyerIntent)], ['query']),
    'adminListAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'adminListAllOffers' : IDL.Func(
        [],
        [IDL.Vec(SellerProductOffer)],
        ['query'],
      ),
    'adminListOperationLogs' : IDL.Func(
        [],
        [IDL.Vec(AdminOperationLog)],
        ['query'],
      ),
    'adminListSessionTxns' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SessionTxn)],
        ['query'],
      ),
    'adminListUsers' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(UserWithoutMobile)],
        ['query'],
      ),
    'adminRecomputeLeaderboard' : IDL.Func([], [OperationResult], []),
    'adminRunAutoMatching' : IDL.Func([], [AutoMatchResult], []),
    'adminSetUserActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBuyerIntent' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createFixture' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Int,
          IDL.Int,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createLeaderboardEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'createMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Float64, IDL.Nat],
        [],
        [],
      ),
    'createOffer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFixture' : IDL.Func([IDL.Nat], [IDL.Opt(Fixture)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserWithoutMobile)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getSessionMerkleRoot' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SessionMerkleRoot)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listFixtures' : IDL.Func([], [IDL.Vec(Fixture)], ['query']),
    'listLeaderboardByFixture' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'listMatchesForSeller' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'listMyIntents' : IDL.Func([], [IDL.Vec(BuyerIntent)], ['query']),
    'listMyMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'listMyOffers' : IDL.Func([], [IDL.Vec(SellerProductOffer)], ['query']),
    'listMySessionTxns' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SessionTxn)],
        ['query'],
      ),
    'listOffersByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SellerProductOffer)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'registerBuyer' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [AppUser],
        [],
      ),
    'registerSeller' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AppUser], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSessionMerkleRoot' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateFixtureStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateIntentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateMatchStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOffer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };