/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminOperationLog {
  'id' : bigint,
  'createdAt' : bigint,
  'summary' : string,
  'triggeredBy' : string,
  'operation' : string,
}
export type AppRole = { 'SELLER' : null } |
  { 'BUYER' : null } |
  { 'VIEWER' : null } |
  { 'ADMIN' : null };
export interface AppUser {
  'id' : bigint,
  'isApproved' : boolean,
  'principal' : Principal,
  'alias' : [] | [string],
  'hashedIdentity' : [] | [string],
  'createdAt' : bigint,
  'role' : AppRole,
  'businessName' : [] | [string],
  'maskedTag' : [] | [string],
  'isActive' : boolean,
  'email' : [] | [string],
  'updatedAt' : bigint,
  'mobile' : [] | [string],
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AutoMatchResult { 'skipped' : bigint, 'matched' : bigint }
export interface BuyerIntent {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'updatedAt' : bigint,
  'constraintsJson' : string,
  'buyerId' : bigint,
  'requestedQuantity' : bigint,
}
export interface Fixture {
  'id' : bigint,
  'groupBSellerIds' : Array<bigint>,
  'status' : string,
  'startsAt' : bigint,
  'groupASellerIds' : Array<bigint>,
  'name' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'updatedAt' : bigint,
  'endsAt' : bigint,
  'scoringFormulaVersion' : string,
}
export interface LeaderboardEntry {
  'id' : bigint,
  'priceScore' : number,
  'fixtureId' : bigint,
  'warrantyScore' : number,
  'overallScore' : number,
  'serviceScore' : number,
  'createdAt' : bigint,
  'rank' : bigint,
  'productId' : bigint,
  'qualityScore' : number,
  'isWinner' : boolean,
  'sellerId' : bigint,
}
export interface Match {
  'id' : bigint,
  'status' : string,
  'fixtureId' : [] | [bigint],
  'createdAt' : bigint,
  'settlementStatus' : string,
  'agreedPrice' : number,
  'buyerIntentId' : bigint,
  'updatedAt' : bigint,
  'sellerProductOfferId' : bigint,
  'quantity' : bigint,
}
export interface OperationResult { 'total' : bigint, 'updated' : bigint }
export interface Product {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'baseSkuCode' : string,
  'description' : string,
  'updatedAt' : bigint,
  'attributes' : string,
  'category' : string,
}
export interface SellerProductOffer {
  'id' : bigint,
  'termsSummary' : string,
  'serviceScore' : bigint,
  'shippingTimeDays' : bigint,
  'createdAt' : bigint,
  'productId' : bigint,
  'isActive' : boolean,
  'qualityScore' : bigint,
  'updatedAt' : bigint,
  'warrantyMonths' : bigint,
  'sellerId' : bigint,
  'priceOffer' : number,
  'priceMrp' : number,
  'quantityAvailable' : bigint,
}
export interface SessionMerkleRoot {
  'id' : bigint,
  'numLeaves' : bigint,
  'createdAt' : bigint,
  'merkleRootHash' : string,
  'sessionId' : string,
}
export interface SessionTxn {
  'id' : bigint,
  'createdAt' : bigint,
  'eventPayload' : string,
  'nonce' : string,
  'buyerId' : [] | [bigint],
  'sellerId' : [] | [bigint],
  'nonceSuffix' : string,
  'sessionId' : string,
  'eventType' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : bigint,
  'isApproved' : boolean,
  'principal' : Principal,
  'alias' : [] | [string],
  'hashedIdentity' : [] | [string],
  'createdAt' : bigint,
  'role' : AppRole,
  'businessName' : [] | [string],
  'maskedTag' : [] | [string],
  'isActive' : boolean,
  'email' : [] | [string],
  'updatedAt' : bigint,
  'mobile' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithoutMobile {
  'id' : bigint,
  'isApproved' : boolean,
  'principal' : Principal,
  'alias' : [] | [string],
  'hashedIdentity' : [] | [string],
  'createdAt' : bigint,
  'role' : AppRole,
  'businessName' : [] | [string],
  'maskedTag' : [] | [string],
  'isActive' : boolean,
  'email' : [] | [string],
  'updatedAt' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveUser' : ActorMethod<[bigint], undefined>,
  'adminListAllIntents' : ActorMethod<[], Array<BuyerIntent>>,
  'adminListAllMatches' : ActorMethod<[], Array<Match>>,
  'adminListAllOffers' : ActorMethod<[], Array<SellerProductOffer>>,
  'adminListOperationLogs' : ActorMethod<[], Array<AdminOperationLog>>,
  'adminListSessionTxns' : ActorMethod<[string], Array<SessionTxn>>,
  'adminListUsers' : ActorMethod<[[] | [string]], Array<UserWithoutMobile>>,
  'adminRecomputeLeaderboard' : ActorMethod<[], OperationResult>,
  'adminRunAutoMatching' : ActorMethod<[], AutoMatchResult>,
  'adminSetUserActive' : ActorMethod<[bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBuyerIntent' : ActorMethod<
    [bigint, bigint, string, string],
    undefined
  >,
  'createFixture' : ActorMethod<
    [string, bigint, Array<bigint>, Array<bigint>, bigint, bigint, string],
    undefined
  >,
  'createLeaderboardEntry' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      number,
      number,
      number,
      number,
      number,
      bigint,
      boolean,
    ],
    undefined
  >,
  'createMatch' : ActorMethod<
    [bigint, bigint, [] | [bigint], number, bigint],
    undefined
  >,
  'createOffer' : ActorMethod<
    [bigint, number, number, bigint, bigint, bigint, bigint, bigint, string],
    undefined
  >,
  'createProduct' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFixture' : ActorMethod<[bigint], [] | [Fixture]>,
  'getMyProfile' : ActorMethod<[], [] | [UserWithoutMobile]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getSessionMerkleRoot' : ActorMethod<[string], [] | [SessionMerkleRoot]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listFixtures' : ActorMethod<[], Array<Fixture>>,
  'listLeaderboardByFixture' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'listMatchesForSeller' : ActorMethod<[], Array<Match>>,
  'listMyIntents' : ActorMethod<[], Array<BuyerIntent>>,
  'listMyMatches' : ActorMethod<[], Array<Match>>,
  'listMyOffers' : ActorMethod<[], Array<SellerProductOffer>>,
  'listMySessionTxns' : ActorMethod<[string], Array<SessionTxn>>,
  'listOffersByProduct' : ActorMethod<[bigint], Array<SellerProductOffer>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'registerBuyer' : ActorMethod<[[] | [string], string, string], AppUser>,
  'registerSeller' : ActorMethod<[string, string, string], AppUser>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSessionMerkleRoot' : ActorMethod<[string, string, bigint], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateFixtureStatus' : ActorMethod<[bigint, string], undefined>,
  'updateIntentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateMatchStatus' : ActorMethod<[bigint, string], undefined>,
  'updateOffer' : ActorMethod<
    [
      bigint,
      bigint,
      number,
      number,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
    ],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];