/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    id: bigint;
    priceScore: number;
    fixtureId: bigint;
    warrantyScore: number;
    overallScore: number;
    serviceScore: number;
    createdAt: bigint;
    rank: bigint;
    productId: bigint;
    qualityScore: number;
    isWinner: boolean;
    sellerId: bigint;
    completedMatchCount: bigint;
}
export interface SellerProductOffer {
    id: bigint;
    termsSummary: string;
    serviceScore: bigint;
    shippingTimeDays: bigint;
    createdAt: bigint;
    productId: bigint;
    isActive: boolean;
    qualityScore: bigint;
    updatedAt: bigint;
    warrantyMonths: bigint;
    sellerId: bigint;
    priceOffer: number;
    priceMrp: number;
    quantityAvailable: bigint;
}
export interface SessionMerkleRoot {
    id: bigint;
    numLeaves: bigint;
    createdAt: bigint;
    merkleRootHash: string;
    sessionId: string;
}
export interface OperationResult {
    total: bigint;
    updated: bigint;
}
export interface Fixture {
    id: bigint;
    groupBSellerIds: Array<bigint>;
    status: string;
    startsAt: bigint;
    groupASellerIds: Array<bigint>;
    name: string;
    createdAt: bigint;
    productId: bigint;
    updatedAt: bigint;
    endsAt: bigint;
    scoringFormulaVersion: string;
}
export interface BuyerIntent {
    id: bigint;
    status: string;
    createdAt: bigint;
    productId: bigint;
    updatedAt: bigint;
    constraintsJson: string;
    buyerId: bigint;
    requestedQuantity: bigint;
}
export interface Match {
    id: bigint;
    status: string;
    fixtureId?: bigint;
    createdAt: bigint;
    settlementStatus: string;
    agreedPrice: number;
    buyerIntentId: bigint;
    updatedAt: bigint;
    sellerProductOfferId: bigint;
    quantity: bigint;
}
export interface AdminOperationLog {
    id: bigint;
    createdAt: bigint;
    summary: string;
    triggeredBy: string;
    operation: string;
}
export interface AutoMatchResult {
    skipped: bigint;
    matched: bigint;
}
export interface AppUser {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias?: string;
    hashedIdentity?: string;
    createdAt: bigint;
    role: AppRole;
    businessName?: string;
    maskedTag?: string;
    isActive: boolean;
    email?: string;
    updatedAt: bigint;
    mobile?: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface SessionTxn {
    id: bigint;
    createdAt: bigint;
    eventPayload: string;
    nonce: string;
    buyerId?: bigint;
    sellerId?: bigint;
    nonceSuffix: string;
    sessionId: string;
    eventType: string;
}
export interface UserWithoutMobile {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias?: string;
    hashedIdentity?: string;
    createdAt: bigint;
    role: AppRole;
    businessName?: string;
    maskedTag?: string;
    isActive: boolean;
    email?: string;
    updatedAt: bigint;
}
export interface UserProfile {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias?: string;
    hashedIdentity?: string;
    createdAt: bigint;
    role: AppRole;
    businessName?: string;
    maskedTag?: string;
    isActive: boolean;
    email?: string;
    updatedAt: bigint;
    mobile?: string;
}
export interface Product {
    id: bigint;
    title: string;
    createdAt: bigint;
    baseSkuCode: string;
    description: string;
    updatedAt: bigint;
    attributes: string;
    category: string;
}
export enum AppRole {
    SELLER = "SELLER",
    BUYER = "BUYER",
    VIEWER = "VIEWER",
    ADMIN = "ADMIN"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminApproveUser(userId: bigint): Promise<void>;
    adminListAllIntents(): Promise<Array<BuyerIntent>>;
    adminListAllMatches(): Promise<Array<Match>>;
    adminListAllOffers(): Promise<Array<SellerProductOffer>>;
    adminListOperationLogs(): Promise<Array<AdminOperationLog>>;
    adminListSessionTxns(sessionId: string): Promise<Array<SessionTxn>>;
    adminListUsers(role: string | null): Promise<Array<UserWithoutMobile>>;
    adminRecomputeLeaderboard(): Promise<OperationResult>;
    adminRunAutoMatching(): Promise<AutoMatchResult>;
    adminSetUserActive(userId: bigint, active: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBuyerIntent(productId: bigint, requestedQuantity: bigint, constraintsJson: string, sessionId: string): Promise<void>;
    createFixture(name: string, productId: bigint, groupASellerIds: Array<bigint>, groupBSellerIds: Array<bigint>, startsAt: bigint, endsAt: bigint, scoringFormulaVersion: string): Promise<void>;
    createLeaderboardEntry(fixtureId: bigint, sellerId: bigint, productId: bigint, priceScore: number, qualityScore: number, serviceScore: number, warrantyScore: number, overallScore: number, rank: bigint, isWinner: boolean): Promise<void>;
    createMatch(buyerIntentId: bigint, sellerProductOfferId: bigint, fixtureId: bigint | null, agreedPrice: number, quantity: bigint): Promise<void>;
    createOffer(productId: bigint, priceMrp: number, priceOffer: number, quantityAvailable: bigint, qualityScore: bigint, serviceScore: bigint, warrantyMonths: bigint, shippingTimeDays: bigint, termsSummary: string): Promise<void>;
    createProduct(title: string, description: string, category: string, baseSkuCode: string, attributes: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFixture(id: bigint): Promise<Fixture | null>;
    getMyProfile(): Promise<UserWithoutMobile | null>;
    getProduct(id: bigint): Promise<Product | null>;
    getSessionMerkleRoot(sessionId: string): Promise<SessionMerkleRoot | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listFixtures(): Promise<Array<Fixture>>;
    listLeaderboardByFixture(fixtureId: bigint): Promise<Array<LeaderboardEntry>>;
    listMatchesForSeller(): Promise<Array<Match>>;
    listMyIntents(): Promise<Array<BuyerIntent>>;
    listMyMatches(): Promise<Array<Match>>;
    listMyOffers(): Promise<Array<SellerProductOffer>>;
    listMySessionTxns(sessionId: string): Promise<Array<SessionTxn>>;
    listOffersByProduct(productId: bigint): Promise<Array<SellerProductOffer>>;
    listProducts(): Promise<Array<Product>>;
    registerBuyer(alias: string | null, mobile: string, sessionId: string): Promise<AppUser>;
    registerSeller(businessName: string, email: string, sessionId: string): Promise<AppUser>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveSessionMerkleRoot(sessionId: string, merkleRootHash: string, numLeaves: bigint): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateFixtureStatus(id: bigint, status: string): Promise<void>;
    updateIntentStatus(id: bigint, status: string): Promise<void>;
    updateMatchStatus(id: bigint, status: string): Promise<void>;
    updateOffer(id: bigint, productId: bigint, priceMrp: number, priceOffer: number, quantityAvailable: bigint, qualityScore: bigint, serviceScore: bigint, warrantyMonths: bigint, shippingTimeDays: bigint, termsSummary: string): Promise<void>;
    updateProduct(id: bigint, title: string, description: string, category: string, baseSkuCode: string, attributes: string): Promise<void>;
}
import type { AppRole as _AppRole, AppUser as _AppUser, ApprovalStatus as _ApprovalStatus, Fixture as _Fixture, Match as _Match, Product as _Product, SessionMerkleRoot as _SessionMerkleRoot, SessionTxn as _SessionTxn, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, UserWithoutMobile as _UserWithoutMobile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminApproveUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveUser(arg0);
            return result;
        }
    }
    async adminListAllIntents(): Promise<Array<BuyerIntent>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllIntents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllIntents();
            return result;
        }
    }
    async adminListAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListAllOffers(): Promise<Array<SellerProductOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllOffers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllOffers();
            return result;
        }
    }
    async adminListOperationLogs(): Promise<Array<AdminOperationLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOperationLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOperationLogs();
            return result;
        }
    }
    async adminListSessionTxns(arg0: string): Promise<Array<SessionTxn>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListSessionTxns(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListSessionTxns(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(arg0: string | null): Promise<Array<UserWithoutMobile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRecomputeLeaderboard(): Promise<OperationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRecomputeLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRecomputeLeaderboard();
            return result;
        }
    }
    async adminRunAutoMatching(): Promise<AutoMatchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRunAutoMatching();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRunAutoMatching();
            return result;
        }
    }
    async adminSetUserActive(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetUserActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetUserActive(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBuyerIntent(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuyerIntent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuyerIntent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createFixture(arg0: string, arg1: bigint, arg2: Array<bigint>, arg3: Array<bigint>, arg4: bigint, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFixture(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFixture(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createLeaderboardEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: bigint, arg9: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLeaderboardEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLeaderboardEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createMatch(arg0: bigint, arg1: bigint, arg2: bigint | null, arg3: number, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createOffer(arg0: bigint, arg1: number, arg2: number, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOffer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOffer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFixture(arg0: bigint): Promise<Fixture | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFixture(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFixture(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserWithoutMobile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionMerkleRoot(arg0: string): Promise<SessionMerkleRoot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionMerkleRoot(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionMerkleRoot(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFixtures(): Promise<Array<Fixture>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFixtures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFixtures();
            return result;
        }
    }
    async listLeaderboardByFixture(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeaderboardByFixture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeaderboardByFixture(arg0);
            return result;
        }
    }
    async listMatchesForSeller(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatchesForSeller();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatchesForSeller();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyIntents(): Promise<Array<BuyerIntent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyIntents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyIntents();
            return result;
        }
    }
    async listMyMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyMatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyMatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyOffers(): Promise<Array<SellerProductOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOffers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOffers();
            return result;
        }
    }
    async listMySessionTxns(arg0: string): Promise<Array<SessionTxn>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMySessionTxns(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMySessionTxns(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOffersByProduct(arg0: bigint): Promise<Array<SellerProductOffer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOffersByProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOffersByProduct(arg0);
            return result;
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async registerBuyer(arg0: string | null, arg1: string, arg2: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBuyer(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_AppUser_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBuyer(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_AppUser_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerSeller(arg0: string, arg1: string, arg2: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSeller(arg0, arg1, arg2);
                return from_candid_AppUser_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSeller(arg0, arg1, arg2);
            return from_candid_AppUser_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSessionMerkleRoot(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSessionMerkleRoot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSessionMerkleRoot(arg0, arg1, arg2);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFixtureStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFixtureStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFixtureStatus(arg0, arg1);
            return result;
        }
    }
    async updateIntentStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIntentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIntentStatus(arg0, arg1);
            return result;
        }
    }
    async updateMatchStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchStatus(arg0, arg1);
            return result;
        }
    }
    async updateOffer(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOffer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOffer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_AppRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AppUser_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUser): AppUser {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SessionTxn_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionTxn): SessionTxn {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserWithoutMobile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserWithoutMobile): UserWithoutMobile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Fixture]): Fixture | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserWithoutMobile]): UserWithoutMobile | null {
    return value.length === 0 ? null : from_candid_UserWithoutMobile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionMerkleRoot]): SessionMerkleRoot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias: [] | [string];
    hashedIdentity: [] | [string];
    createdAt: bigint;
    role: _AppRole;
    businessName: [] | [string];
    maskedTag: [] | [string];
    isActive: boolean;
    email: [] | [string];
    updatedAt: bigint;
}): {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias?: string;
    hashedIdentity?: string;
    createdAt: bigint;
    role: AppRole;
    businessName?: string;
    maskedTag?: string;
    isActive: boolean;
    email?: string;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        principal: value.principal,
        alias: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.alias)),
        hashedIdentity: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.hashedIdentity)),
        createdAt: value.createdAt,
        role: from_candid_AppRole_n13(_uploadFile, _downloadFile, value.role),
        businessName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.businessName)),
        maskedTag: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.maskedTag)),
        isActive: value.isActive,
        email: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias: [] | [string];
    hashedIdentity: [] | [string];
    createdAt: bigint;
    role: _AppRole;
    businessName: [] | [string];
    maskedTag: [] | [string];
    isActive: boolean;
    email: [] | [string];
    updatedAt: bigint;
    mobile: [] | [string];
}): {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias?: string;
    hashedIdentity?: string;
    createdAt: bigint;
    role: AppRole;
    businessName?: string;
    maskedTag?: string;
    isActive: boolean;
    email?: string;
    updatedAt: bigint;
    mobile?: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        principal: value.principal,
        alias: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.alias)),
        hashedIdentity: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.hashedIdentity)),
        createdAt: value.createdAt,
        role: from_candid_AppRole_n13(_uploadFile, _downloadFile, value.role),
        businessName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.businessName)),
        maskedTag: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.maskedTag)),
        isActive: value.isActive,
        email: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt,
        mobile: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.mobile))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n30(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    fixtureId: [] | [bigint];
    createdAt: bigint;
    settlementStatus: string;
    agreedPrice: number;
    buyerIntentId: bigint;
    updatedAt: bigint;
    sellerProductOfferId: bigint;
    quantity: bigint;
}): {
    id: bigint;
    status: string;
    fixtureId?: bigint;
    createdAt: bigint;
    settlementStatus: string;
    agreedPrice: number;
    buyerIntentId: bigint;
    updatedAt: bigint;
    sellerProductOfferId: bigint;
    quantity: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        fixtureId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.fixtureId)),
        createdAt: value.createdAt,
        settlementStatus: value.settlementStatus,
        agreedPrice: value.agreedPrice,
        buyerIntentId: value.buyerIntentId,
        updatedAt: value.updatedAt,
        sellerProductOfferId: value.sellerProductOfferId,
        quantity: value.quantity
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: bigint;
    eventPayload: string;
    nonce: string;
    buyerId: [] | [bigint];
    sellerId: [] | [bigint];
    nonceSuffix: string;
    sessionId: string;
    eventType: string;
}): {
    id: bigint;
    createdAt: bigint;
    eventPayload: string;
    nonce: string;
    buyerId?: bigint;
    sellerId?: bigint;
    nonceSuffix: string;
    sessionId: string;
    eventType: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        eventPayload: value.eventPayload,
        nonce: value.nonce,
        buyerId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.buyerId)),
        sellerId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.sellerId)),
        nonceSuffix: value.nonceSuffix,
        sessionId: value.sessionId,
        eventType: value.eventType
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SELLER: null;
} | {
    BUYER: null;
} | {
    VIEWER: null;
} | {
    ADMIN: null;
}): AppRole {
    return "SELLER" in value ? AppRole.SELLER : "BUYER" in value ? AppRole.BUYER : "VIEWER" in value ? AppRole.VIEWER : "ADMIN" in value ? AppRole.ADMIN : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionTxn>): Array<SessionTxn> {
    return value.map((x)=>from_candid_SessionTxn_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserWithoutMobile>): Array<UserWithoutMobile> {
    return value.map((x)=>from_candid_UserWithoutMobile_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias?: string;
    hashedIdentity?: string;
    createdAt: bigint;
    role: AppRole;
    businessName?: string;
    maskedTag?: string;
    isActive: boolean;
    email?: string;
    updatedAt: bigint;
    mobile?: string;
}): {
    id: bigint;
    isApproved: boolean;
    principal: Principal;
    alias: [] | [string];
    hashedIdentity: [] | [string];
    createdAt: bigint;
    role: _AppRole;
    businessName: [] | [string];
    maskedTag: [] | [string];
    isActive: boolean;
    email: [] | [string];
    updatedAt: bigint;
    mobile: [] | [string];
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        principal: value.principal,
        alias: value.alias ? candid_some(value.alias) : candid_none(),
        hashedIdentity: value.hashedIdentity ? candid_some(value.hashedIdentity) : candid_none(),
        createdAt: value.createdAt,
        role: to_candid_AppRole_n35(_uploadFile, _downloadFile, value.role),
        businessName: value.businessName ? candid_some(value.businessName) : candid_none(),
        maskedTag: value.maskedTag ? candid_some(value.maskedTag) : candid_none(),
        isActive: value.isActive,
        email: value.email ? candid_some(value.email) : candid_none(),
        updatedAt: value.updatedAt,
        mobile: value.mobile ? candid_some(value.mobile) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    SELLER: null;
} | {
    BUYER: null;
} | {
    VIEWER: null;
} | {
    ADMIN: null;
} {
    return value == AppRole.SELLER ? {
        SELLER: null
    } : value == AppRole.BUYER ? {
        BUYER: null
    } : value == AppRole.VIEWER ? {
        VIEWER: null
    } : value == AppRole.ADMIN ? {
        ADMIN: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
